apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2020-07-11T18:49:00Z"
  generation: 1
  labels:
    app: web
  name: web
  namespace: default
  resourceVersion: "96891"
  selfLink: /apis/apps/v1/namespaces/default/deployments/web
  uid: adf3bb40-e318-4735-a49d-707e0ac9feea
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
